# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20170808_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_device',
            name='date',
        ),
    ]
